# Generated by Django 5.1.6 on 2025-02-17 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='orders', through='pos.OrderProduct', to='pos.product'),
        ),
    ]
